http_server_host = '127.0.0.1'
http_server_port = 7001
ipfs_seed = 2
ipfs_port = 37001
ipfs_path = 'avail_ipfs_node_1'
full_node_rpc = ['http://127.0.0.1:9933']
full_node_ws = ['ws://127.0.0.1:9944']
app_id = 0
confidence = 92.0
bootstraps = [["12D3KooWMm1c4pzeLPGkkCJMAgFbsfQ8xmVDusg272icWsaNHWzN", "/ip4/127.0.0.1/tcp/37000"]]
avail_path = 'avail_light_client_1'
log_level = 'info'
